# Generated by Django 5.2.10 on 2026-01-15 09:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание точки')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Владелец точки')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'indexes': [models.Index(fields=['created_at'], name='points_poin_created_7d0bae_idx'), models.Index(fields=['updated_at'], name='points_poin_updated_fb217a_idx')],
            },
        ),
    ]
