# Generated by Django 5.2.10 on 2026-01-15 12:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='point_messages_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='point_messages_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='point',
            name='points_poin_updated_fb217a_idx',
        ),
        migrations.AddIndex(
            model_name='point',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='points_poin_locatio_e21e54_gist'),
        ),
        migrations.AddField(
            model_name='pointmessage',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='points.point'),
        ),
        migrations.AddField(
            model_name='pointmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
